# Generated by Django 5.2 on 2025-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pastor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('audio_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
